import { Company } from "@/types/types";

export const dummyCompanies: Company[] = [
  {
    id: "1",
    name: "Tech Innovations",
    location: "San Francisco, CA",
    yearsOfOperation: 5,
    employeeCount: 50,
    industry: "software",
    fundingRound: "seriesA",
    profilePhotoIds: ["photo1", "photo2"],
    prompts: [
      { question: "What is your mission?", answer: "To innovate technology." },
      { question: "What products do you offer?", answer: "Software solutions." },
    ],
  },
  {
    id: "2",
    name: "Finance Solutions",
    location: "New York, NY",
    yearsOfOperation: 10,
    employeeCount: 200,
    industry: "finance",
    fundingRound: "seriesB",
    profilePhotoIds: ["photo3", "photo4"],
    prompts: [
      { question: "What is your mission?", answer: "To provide financial clarity." },
      { question: "What services do you offer?", answer: "Investment advice." },
    ],
  },
  {
    id: "3",
    name: "Creative Designs",
    location: "Austin, TX",
    yearsOfOperation: 3,
    employeeCount: 30,
    industry: "design",
    fundingRound: "seed",
    profilePhotoIds: ["photo5", "photo6"],
    prompts: [
      { question: "What is your mission?", answer: "To create stunning visuals." },
      { question: "What do you specialize in?", answer: "Graphic design." },
    ],
  },
  {
    id: "4",
    name: "HealthTech Corp",
    location: "Boston, MA",
    yearsOfOperation: 7,
    employeeCount: 150,
    industry: "software",
    fundingRound: "seriesC",
    profilePhotoIds: ["photo7", "photo8"],
    prompts: [
      { question: "What is your mission?", answer: "To improve healthcare through technology." },
      { question: "What products do you offer?", answer: "Health management software." },
    ],
  },
  {
    id: "5",
    name: "EcoFinance",
    location: "Seattle, WA",
    yearsOfOperation: 4,
    employeeCount: 80,
    industry: "finance",
    fundingRound: "seriesA",
    profilePhotoIds: ["photo9", "photo10"],
    prompts: [
      { question: "What is your mission?", answer: "To promote sustainable investments." },
      { question: "What services do you offer?", answer: "Eco-friendly financial planning." },
    ],
  },
  {
    id: "6",
    name: "Design Studio",
    location: "Los Angeles, CA",
    yearsOfOperation: 2,
    employeeCount: 20,
    industry: "design",
    fundingRound: "seed",
    profilePhotoIds: ["photo11", "photo12"],
    prompts: [
      { question: "What is your mission?", answer: "To bring ideas to life through design." },
      { question: "What do you specialize in?", answer: "Web design." },
    ],
  },
  {
    id: "7",
    name: "FinTech Innovations",
    location: "Chicago, IL",
    yearsOfOperation: 6,
    employeeCount: 120,
    industry: "finance",
    fundingRound: "seriesB",
    profilePhotoIds: ["photo13", "photo14"],
    prompts: [
      { question: "What is your mission?", answer: "To revolutionize financial services." },
      { question: "What products do you offer?", answer: "Mobile banking solutions." },
    ],
  },
  {
    id: "8",
    name: "Software Solutions",
    location: "Denver, CO",
    yearsOfOperation: 8,
    employeeCount: 300,
    industry: "software",
    fundingRound: "seriesC",
    profilePhotoIds: ["photo15", "photo16"],
    prompts: [
      { question: "What is your mission?", answer: "To provide robust software solutions." },
      { question: "What do you specialize in?", answer: "Enterprise software." },
    ],
  },
  {
    id: "9",
    name: "Creative Agency",
    location: "Miami, FL",
    yearsOfOperation: 1,
    employeeCount: 10,
    industry: "design",
    fundingRound: "seed",
    profilePhotoIds: ["photo17", "photo18"],
    prompts: [
      { question: "What is your mission?", answer: "To inspire through creativity." },
      { question: "What services do you offer?", answer: "Branding and marketing." },
    ],
  },
  {
    id: "10",
    name: "Tech Finance",
    location: "Atlanta, GA",
    yearsOfOperation: 9,
    employeeCount: 250,
    industry: "finance",
    fundingRound: "seriesB",
    profilePhotoIds: ["photo19", "photo20"],
    prompts: [
      { question: "What is your mission?", answer: "To integrate technology with finance." },
      { question: "What services do you offer?", answer: "Financial consulting." },
    ],
  },
];
